### ISSUE TITLE
Use a real namespace name for tutorial

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#131]
**Describe the bug**
The tutorial says to create a namespace called "{tutorial namespace}", where it is implied that this is a placeholder for a string chosen by the user. I suggest using a definite, valid namespace string e.g. "tutorial"

1. Using the {} placeholder means the user cannot cut/paste commands that include the namespace without manual editing.
2. Inexperienced users are already being flooded with new syntax, they may not realize that "{}" is not supposed to be typed literally, which will cause needless confusion and frustration.

**Comment by alanconway** [comment]
Looking at the site.yml I see that this is another substitution bug - {tutorial-namespace} is supposed to be substituted by asciidoctor. Not sure why it isn't in my case. 
This is similar to to #130 - browser & js module versions are provided there.

**Comment by kameshsampath** [comment]
@alanconway  -  we need to do this because the tutorial needs to be adapted for multiple workshops where we might need to change the tutorial namespace as in shared openshift or kubernetes cluster we cant have same namespace/projects. Please ensure that `{tutorial-namespace}` is added like how its in the site.yml in your `dev-site.yml` as well. As @syedriko  said in another issue we could push dev-site.yml as well to the repo.
