### ISSUE TITLE
Update the list of prerequisite tools

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#80]
- Add git to the list of prerequisites
- I did not notice any mentions in the tutorial of xmlstarlet, kubectx or kubens that are listed as prereqs.
- Maybe pick of one httpie or curl?

**Comment by rhuss** [comment]
>     * I did not notice any mentions in the tutorial of xmlstarlet, kubectx or kubens that are listed as prereqs.

haven't seen its usage, too. But maybe it would make sense to adapt some examples to us `kubens` instead of using `--namespace knative-tutorial` in the commands. On the other hand, it introduces a new possibility to fail (when you miss entering `kubens`) so we probably shouldn't use it.

>     * Maybe pick of one httpie or curl?

Agreed to stick to one only. Showing two equivalent examples with curl and httpie doing the same dilutes the purpose of this tutorial and is more distracting than helpful.

**Comment by kameshsampath** [comment]
Few of them were in addressed in earlier PRS.  Still need to work on removing curl.
